# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4076e96d011317e09e86b93711f76eabfb54b633b4a4650ecbeebcea0812adc16e660ab39c813ab90b82c13dd8a4efd69e4c2265cb070b5ca402f7dbf1bb6c3b

test:
  secret_key_base: 34b7192a6451633c1076c1b179a5ee3009fb129d3827d7ad6107fe45dfafbced50cac779b33128bac8c2b7e74fe4791e62bc03ac21d26c3116d0bdc9696703e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
